name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          npm install
          npm test -- --coverage

      # Set up SonarCloud environment variables
      - name: Set up SonarCloud Analysis Environment
        run: |
          echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV

      # Run SonarCloud analysis
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
